version: '3.8'
services:
    stage:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - '80:3002'
        volumes:
            - .:/home/node/app
networks:
    default:
        driver: bridge